config/routes.rb
Rails.application.routes.draw do
  get 'regions/index'
  root 'regions#index'

  resources :regions, only: [:index, :show] do
  end

  resources :places do 
    get :search, on: :collection
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/camera.rb
# == Schema Information
#
# Table name: cameras
#
#  id         :integer          not null, primary key
#  working    :integer
#  fs         :integer
#  kind       :integer
#  place_id   :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Camera < ApplicationRecord
  belongs_to :place

  scope :working, ->  { where('working > ? ', 0) }
  scope :fs, ->  { where('fs > ? ', 0) }

  validates :fs, :numericality => { greater_than_or_equal_to: 0 }
  validates :working, :numericality => { greater_than_or_equal_to: 0 }

  enum kind: [:termica, :fija, :domo, :ptz, :lpr]

  def kind_format
    return 'Cam. Termica.' if self.kind == 'termica'
    return 'Cam. Fija.' if self.kind == 'fija'
    return 'Cam. Mini Domo.' if self.kind == 'domo'
    return 'Cam. PTZ.' if self.kind == 'ptz'
    return 'Cam. LPR.' if self.kind == 'lpr'
  end

end

app/models/institution.rb
# == Schema Information
#
# Table name: institutions
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Institution < ApplicationRecord
    has_many :places

    validates :name, presence:true

    def cameras
        self.places.reduce(0) { |sum, place| sum + place.total }
    end

end

app/models/place.rb
# == Schema Information
#
# Table name: places
#
#  id         :integer          not null, primary key
#  name       :string
#  region_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Place < ApplicationRecord
  belongs_to :region
  has_many :cameras
  has_many :reports
  has_one :report, -> { order("id DESC") }

  after_create :create_cameras

  accepts_nested_attributes_for :report
  accepts_nested_attributes_for :cameras
  

  def working
    self.cameras.reduce(0) { |sum, camera| sum + camera.working }
  end

  def fs
    self.cameras.reduce(0) { |sum, camera| sum + camera.fs }
  end

  def total
    self.cameras.reduce(0) { |sum, camera| sum + (camera.fs + camera.working) }
  end

  def create_cameras
    (0..4).each { |c|  Camera.create(kind:c, place: self, working:0, fs:0) } unless self.cameras.any?
  end

  def fs_percentage
    begin
        (self.fs * 100)/ self.total
    rescue
        0
    end
  end 
  
  def percentage_css_class
    return 'text-red-400 ' if self.fs_percentage > 70
    return 'text-yellow-600 ' if self.fs_percentage > 40
    'text-green-400 '
  end
end

app/models/region.rb
# == Schema Information
#
# Table name: regions
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Region < ApplicationRecord
  has_many :places

  validates :name, presence:true

  def total
    self.places.reduce(0) { |sum, place| sum + place.total }
  end

  def fs 
    self.places.reduce(0) { |sum, place| sum + place.fs }
  end

  def working
    self.places.reduce(0) { |sum, place| sum + place.working }
  end

  def fs_percentage
    begin
        (self.fs * 100)/ self.total
    rescue
        0
    end
  end

  def percentage_css_class
    return 'text-red-600 ' if self.fs_percentage > 70
    return 'text-yellow-600 ' if self.fs_percentage > 40
    'text-green-500'
  end

end

app/models/report.rb
# == Schema Information
#
# Table name: reports
#
#  id         :integer          not null, primary key
#  comments   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  place_id   :integer          not null
#
class Report < ApplicationRecord

    belongs_to :place
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def welcome
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: %i[ show edit update destroy ]

  # GET /places or /places.json
  def index
    @places = Place.all
  end

  # GET /places/1 or /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places or /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to place_url(@place), notice: "Place was successfully created." }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1 or /places/1.json
  def update
    respond_to do |format|
        if @place.update(place_params)
            format.html { redirect_to place_url(@place), notice: "Place was successfully updated." }
            format.json { render :show, status: :ok, location: @place }
        else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @place.errors, status: :unprocessable_entity }
        end
    end
  end

  def search
    @q = params[:q]
    @places = Place.where('name LIKE ?', "%#{@q}%")
  end

  # DELETE /places/1 or /places/1.json
  def destroy
    @place.destroy

    respond_to do |format|
      format.html { redirect_to places_url, notice: "Place was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def place_params
      params.require(:place).permit(:name, :institution_id, :q,  cameras_attributes:[:id, :working, :fs])
    end
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController	

    before_action :set_region, only: [:show]
    
    def index
        @regions = Region.all.order('name ASC')
    end

    def show
        @Region = Region.all
    end

    private
    
    def set_region
        @region = Region.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/institutions/show.html.erb
<section class="bg-white">
  <div class="container px-4 mx-auto">
    <div class="px-6 pb-6 pt-4 bg-white border shadow rounded">
      <div class="flex flex-wrap items-center mb-3">
        <div>
          <div class="">
            <div>
                <%= link_to 'Regresar al listado', root_path, class:"font-medium text-indigo-500 hover:underline"%>
            </div>
            <div>
                <h3 class="mr-2 text-xl font-bold">Instalaciones para <%= @institution.name %></h3>
            </div>
          </div>
        </div>
      </div>

    <% @institution.places.each do |place| %>
        <%= link_to edit_place_path(place) do %>
            <div class="flex justify-between items-center mb-2 p-4 bg-gray-50 rounded">
                <div class="flex items-center">
                <span class="inline-flex w-10 h-10 mr-3 justify-center items-center bg-purple-50 rounded">
                    <svg width="16" height="20" viewBox="0 0 16 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M9 12H5C4.73478 12 4.48043 12.1054 4.29289 12.2929C4.10536 12.4804 4 12.7348 4 13C4 13.2652 4.10536 13.5196 4.29289 13.7071C4.48043 13.8946 4.73478 14 5 14H9C9.26522 14 9.51957 13.8946 9.70711 13.7071C9.89464 13.5196 10 13.2652 10 13C10 12.7348 9.89464 12.4804 9.70711 12.2929C9.51957 12.1054 9.26522 12 9 12ZM13 2H11.82C11.6137 1.41645 11.2319 0.910998 10.7271 0.552938C10.2222 0.194879 9.61894 0.00173951 9 0H7C6.38106 0.00173951 5.7778 0.194879 5.27293 0.552938C4.76807 0.910998 4.38631 1.41645 4.18 2H3C2.20435 2 1.44129 2.31607 0.87868 2.87868C0.316071 3.44129 0 4.20435 0 5V17C0 17.7956 0.316071 18.5587 0.87868 19.1213C1.44129 19.6839 2.20435 20 3 20H13C13.7956 20 14.5587 19.6839 15.1213 19.1213C15.6839 18.5587 16 17.7956 16 17V5C16 4.20435 15.6839 3.44129 15.1213 2.87868C14.5587 2.31607 13.7956 2 13 2ZM6 3C6 2.73478 6.10536 2.48043 6.29289 2.29289C6.48043 2.10536 6.73478 2 7 2H9C9.26522 2 9.51957 2.10536 9.70711 2.29289C9.89464 2.48043 10 2.73478 10 3V4H6V3ZM14 17C14 17.2652 13.8946 17.5196 13.7071 17.7071C13.5196 17.8946 13.2652 18 13 18H3C2.73478 18 2.48043 17.8946 2.29289 17.7071C2.10536 17.5196 2 17.2652 2 17V5C2 4.73478 2.10536 4.48043 2.29289 4.29289C2.48043 4.10536 2.73478 4 3 4H4V5C4 5.26522 4.10536 5.51957 4.29289 5.70711C4.48043 5.89464 4.73478 6 5 6H11C11.2652 6 11.5196 5.89464 11.7071 5.70711C11.8946 5.51957 12 5.26522 12 5V4H13C13.2652 4 13.5196 4.10536 13.7071 4.29289C13.8946 4.48043 14 4.73478 14 5V17ZM11 8H5C4.73478 8 4.48043 8.10536 4.29289 8.29289C4.10536 8.48043 4 8.73478 4 9C4 9.26522 4.10536 9.51957 4.29289 9.70711C4.48043 9.89464 4.73478 10 5 10H11C11.2652 10 11.5196 9.89464 11.7071 9.70711C11.8946 9.51957 12 9.26522 12 9C12 8.73478 11.8946 8.48043 11.7071 8.29289C11.5196 8.10536 11.2652 8 11 8Z" fill="#382CDD"></path>
                    </svg>
                </span>
                <div>
                    <h4 class="text-sm font-medium"><%= place.name %></h4>
                    <p class="text-xs text-gray-500"><%= place.total %> Cámaras.</p>
                </div>
                </div>
                <div class="flex items-center">
                <!-- 
                    <a href="#">
                        <svg width="16" height="4" viewBox="0 0 16 4" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M8 0.333344C7.67037 0.333344 7.34813 0.431092 7.07405 0.614228C6.79997 0.797363 6.58635 1.05766 6.4602 1.36221C6.33406 1.66675 6.30105 2.00186 6.36536 2.32516C6.42967 2.64846 6.5884 2.94543 6.82149 3.17852C7.05458 3.41161 7.35155 3.57034 7.67485 3.63465C7.99815 3.69896 8.33326 3.66596 8.63781 3.53981C8.94235 3.41366 9.20265 3.20004 9.38578 2.92596C9.56892 2.65188 9.66667 2.32965 9.66667 2.00001C9.66667 1.55798 9.49107 1.13406 9.17851 0.821499C8.86595 0.508939 8.44203 0.333344 8 0.333344ZM2.16667 0.333344C1.83703 0.333344 1.5148 0.431092 1.24072 0.614228C0.966635 0.797363 0.753014 1.05766 0.626868 1.36221C0.500722 1.66675 0.467717 2.00186 0.532025 2.32516C0.596334 2.64846 0.755068 2.94543 0.988156 3.17852C1.22124 3.41161 1.51822 3.57034 1.84152 3.63465C2.16482 3.69896 2.49993 3.66596 2.80447 3.53981C3.10902 3.41366 3.36931 3.20004 3.55245 2.92596C3.73559 2.65188 3.83333 2.32965 3.83333 2.00001C3.83333 1.55798 3.65774 1.13406 3.34518 0.821499C3.03262 0.508939 2.6087 0.333344 2.16667 0.333344ZM13.8333 0.333344C13.5037 0.333344 13.1815 0.431092 12.9074 0.614228C12.6333 0.797363 12.4197 1.05766 12.2935 1.36221C12.1674 1.66675 12.1344 2.00186 12.1987 2.32516C12.263 2.64846 12.4217 2.94543 12.6548 3.17852C12.8879 3.41161 13.1849 3.57034 13.5082 3.63465C13.8315 3.69896 14.1666 3.66596 14.4711 3.53981C14.7757 3.41366 15.036 3.20004 15.2191 2.92596C15.4023 2.65188 15.5 2.32965 15.5 2.00001C15.5 1.55798 15.3244 1.13406 15.0118 0.821499C14.6993 0.508939 14.2754 0.333344 13.8333 0.333344Z" fill="#67798E"></path>
                        </svg>
                    </a>
                -->
                </div>
            </div>
        <% end %>
        
    <% end %>
      
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rsf</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <section class="py-8 px-6">
        <div class="flex flex-wrap items-center">
            <div class="w-full lg:w-auto flex items-center mb-4 lg:mb-0">
                <h2 class="text-2xl font-bold"></h2>
            </div>
            <div class="w-full md:w-1/2 lg:w-auto flex py-2 px-4 mb-4 md:mb-0 md:mr-4 md:ml-auto border rounded bg-white">

                <%= form_tag search_places_path, method: :get, remote: false do %>
                    <%= text_field_tag(:q, params[:q], placeholder:"Busqueda por nombre", class:"text-sm placeholder-gray-500") %>
                    <%= button_tag type: "submit" do %>
                        <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M18.0921 16.9083L15.0004 13.8417C16.2005 12.3453 16.7817 10.4461 16.6244 8.53441C16.4672 6.62274 15.5835 4.84398 14.155 3.56386C12.7265 2.28375 10.8619 1.59958 8.94451 1.65205C7.02711 1.70452 5.20268 2.48963 3.84636 3.84594C2.49004 5.20226 1.70493 7.02669 1.65247 8.94409C1.6 10.8615 2.28416 12.7261 3.56428 14.1546C4.84439 15.583 6.62316 16.4668 8.53482 16.624C10.4465 16.7812 12.3457 16.2001 13.8421 15L16.9087 18.0667C16.9862 18.1448 17.0784 18.2068 17.1799 18.2491C17.2815 18.2914 17.3904 18.3132 17.5004 18.3132C17.6104 18.3132 17.7193 18.2914 17.8209 18.2491C17.9224 18.2068 18.0146 18.1448 18.0921 18.0667C18.2423 17.9113 18.3262 17.7036 18.3262 17.4875C18.3262 17.2714 18.2423 17.0637 18.0921 16.9083ZM9.16708 15C8.01335 15 6.88554 14.6579 5.92625 14.0169C4.96696 13.3759 4.21929 12.4649 3.77778 11.399C3.33627 10.3331 3.22075 9.16019 3.44583 8.02863C3.67091 6.89708 4.22648 5.85767 5.04229 5.04187C5.85809 4.22606 6.89749 3.67049 8.02905 3.44541C9.1606 3.22033 10.3335 3.33585 11.3994 3.77736C12.4653 4.21887 13.3763 4.96654 14.0173 5.92583C14.6583 6.88512 15.0004 8.01293 15.0004 9.16666C15.0004 10.7138 14.3858 12.1975 13.2919 13.2914C12.1979 14.3854 10.7142 15 9.16708 15Z" fill="#382CDD"></path>
                        </svg>
                    <% end %>
                <% end %>
            </div>
            <%= link_to root_path, class:"md:w-auto flex items-center py-2 px-4 rounded bg-indigo-500 hover:bg-indigo-600 text-white text-sm font-medium" do %>
                <span class="inline-block mr-1">
                </span>
                <span>Listado</span>
            <% end %>
        </div>
    </section>
    
    <%= yield %>        
    
  </body>
</html>

app/views/main/welcome.html.erb
<h1>Main#welcome</h1>
<p>Find me in app/views/main/welcome.html.erb</p>

app/views/places/_form.html.erb
<%= form_with model:@place, local: true  do |form| %>

  <%= form.fields_for :cameras do |f| %>
    <div class="bg-gray-50 mt-4 py-4">
        <p class="text-base text-gray-500 px-4"><%= f.object.kind_format %></p>
        <div class="flex flex-wrap">
            <div class="w-full md:w-1/2 px-4">
                <div class="">
                    <%= f.label "Operativas" %>
                    <%= f.number_field :working, class:"appearance-none block w-full py-3 px-4 leading-tight text-white-700 bg-white-50 focus:bg-white border border-white-200 focus:border-white-500 rounded" %>
                </div>
            </div>
            <div class="w-full md:w-1/2 px-4">
                <div class="">
                    <%= f.label "Fuera de servicio" %>
                    <%= f.number_field :fs, class:"appearance-none block w-full py-3 px-4 leading-tight text-white-700 bg-white-50 focus:bg-white border border-white-200 focus:border-white-500 rounded" %>
                </div>
            </div>
        </div>
    </div>
    
  <% end %>

  <div class="mt-4">
    <%= form.submit 'Guardar', class:"cursor-pointer inline-block  py-4 px-8 leading-none text-white bg-indigo-600 hover:bg-indigo-700 font-semibold rounded shadow" %>
  </div>
<% end %>

app/views/places/_place.html.erb
<div id="<%= dom_id place %>">
  <p>
    <strong>Name:</strong>
    <%= place.name %>
  </p>

  <p>
    <strong>Institution:</strong>
    <%= place.institution_id %>
  </p>

</div>

app/views/places/edit.html.erb
<section class="bg-white mb-4">
  <div class="container px-4 mx-auto">
    <div>
        <%= link_to 'Regresar', region_path(@place.region), class:"font-medium text-indigo-500 hover:underline"%>
    </div>
    <div>
        <h2 class="mr-2 text-xl font-bold">Editar Cámaras <%= @place.name %></h2>
    </div>
    <%= render "form", place: @place %>
  </div>
</section>

app/views/places/new.html.erb
<h1>New place</h1>

<%= render "form", place: @place %>

<br>

<div>
  <%= link_to "Back to places", places_path %>
</div>

app/views/places/show.html.erb
<section class="">
  <div class="container px-4 mx-auto">
    <div class="flex flex-wrap -m-4">
      <div class="w-full p-4">
        <div class="p-6 bg-white shadow rounded">
          <div class="flex justify-between mb-2">
            <div class="flex items-center">
                <div class="flex mb-2">
                    <h3 class="font-medium"><%= @place.name %></h3>
                </div>
            </div>
          </div>
          <div class="flex mb-2 justify-between items-center">
            <div class="flex items-center">
              <h4 class="text-base text-gray-500">Región</h4>
            </div>
            <%= link_to region_path(@place.region), class:"font-medium text-indigo-500 hover:underline" do %>
              <span class="text-base"><%= @place.region.name %></span>
            <% end %>
          </div>
          <hr class="mt-4 mb-4">
          <div class="flex mb-2 justify-between items-center">
            <div class="flex items-center">
              <h4 class="text-base text-gray-500">Cámaras totales</h4>
            </div>
            <span class="text-base"><%= @place.total %></span>
          </div>
          <div class="flex mb-2 justify-between items-center">
            <div class="flex items-center">
              <h4 class="text-base text-gray-500">Cámaras operativas</h4>
            </div>
            <span class="text-base"><%= @place.working %></span>
          </div>
          <div class="flex mb-2 justify-between items-center">
            <div class="flex items-center">
              <h4 class="text-base text-gray-500">Cámaras fuera de servicio</h4>
            </div>
            <span class="text-base"><%= @place.fs %></span>
          </div>
          <div class="flex mb-2 justify-between items-center">
            <div class="flex items-center">
              <h4 class="text-base text-gray-500">Porcentaje fuera de servicio</h4>
            </div>
            <span class="text-base font-mono <%= @place.percentage_css_class %>"><%= @place.fs_percentage %>%</span>
          </div>
          <div class="flex flex-wrap -mx-2 mt-4">
            <div class="w-full md:w-1/2 px-2 mb-2 md:mb-0">
              <%= link_to edit_place_path(@place), class:"flex justify-center py-2 text-base text-white bg-indigo-500 hover:bg-indigo-600 rounded transition duration-200" do %>
                <span>Editar</span>
              <% end %>
            </div>
          </div>
        </div>
      </div> 
    </div>
  </div>
</section>

app/views/regions/show.html.erb
<section class="bg-white">
  <div class="container px-4 mx-auto">
    <div class="px-6 pb-6 pt-4 bg-white border shadow rounded">

      <div class="mb-4">
        <%= link_to regions_path, class:"font-medium text-indigo-500 hover:underline" do %>
          <h3 class="font-medium">Listado de regiones</h3>
        <% end %>
      </div>

      <div class="mb-4">
        <h3 class="font-medium"><%= @region.name %></h3>
      </div>

      <div class="p-6 bg-white shadow rounded">
        <div class="flex mb-2 justify-between items-center">
          <div class="flex items-center">
            <h4 class="text-base text-gray-500">Cámaras totales</h4>
          </div>
            <span class="text-base"><%= @region.total %></span>
        </div>

        <div class="flex mb-2 justify-between items-center">
          <div class="flex items-center">
            <h4 class="text-base text-gray-500">Cámaras operativas</h4>
          </div>
            <span class="text-base"><%= @region.working %></span>
        </div>

        <div class="flex mb-2 justify-between items-center">
          <div class="flex items-center">
            <h4 class="text-base text-gray-500">Cámaras fuera de servicio</h4>
          </div>
            <span class="text-base"><%= @region.fs %></span>
        </div>

        <div class="flex mb-2 justify-between items-center">
          <div class="flex items-center">
            <h4 class="text-gray-500">Porcentaje fuera de servicio</h4>
          </div>
<span class="text-base <%= @region.percentage_css_class %>"><%= @region.fs_percentage %>%</span>
        </div>

      </div>

      <div class="mt-4">
        <% @region.places.each do |place| %>
          <%= link_to place_path(place) do %>
            <div class="flex justify-between items-center mb-2 p-4 bg-gray-50 rounded">
              <div class="flex items-center">
                <span class="inline-flex w-10 h-10 mr-3 justify-center items-center bg-purple-50 rounded">
                  <svg width="16" height="20" viewBox="0 0 16 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M9 12H5C4.73478 12 4.48043 12.1054 4.29289 12.2929C4.10536 12.4804 4 12.7348 4 13C4 13.2652 4.10536 13.5196 4.29289 13.7071C4.48043 13.8946 4.73478 14 5 14H9C9.26522 14 9.51957 13.8946 9.70711 13.7071C9.89464 13.5196 10 13.2652 10 13C10 12.7348 9.89464 12.4804 9.70711 12.2929C9.51957 12.1054 9.26522 12 9 12ZM13 2H11.82C11.6137 1.41645 11.2319 0.910998 10.7271 0.552938C10.2222 0.194879 9.61894 0.00173951 9 0H7C6.38106 0.00173951 5.7778 0.194879 5.27293 0.552938C4.76807 0.910998 4.38631 1.41645 4.18 2H3C2.20435 2 1.44129 2.31607 0.87868 2.87868C0.316071 3.44129 0 4.20435 0 5V17C0 17.7956 0.316071 18.5587 0.87868 19.1213C1.44129 19.6839 2.20435 20 3 20H13C13.7956 20 14.5587 19.6839 15.1213 19.1213C15.6839 18.5587 16 17.7956 16 17V5C16 4.20435 15.6839 3.44129 15.1213 2.87868C14.5587 2.31607 13.7956 2 13 2ZM6 3C6 2.73478 6.10536 2.48043 6.29289 2.29289C6.48043 2.10536 6.73478 2 7 2H9C9.26522 2 9.51957 2.10536 9.70711 2.29289C9.89464 2.48043 10 2.73478 10 3V4H6V3ZM14 17C14 17.2652 13.8946 17.5196 13.7071 17.7071C13.5196 17.8946 13.2652 18 13 18H3C2.73478 18 2.48043 17.8946 2.29289 17.7071C2.10536 17.5196 2 17.2652 2 17V5C2 4.73478 2.10536 4.48043 2.29289 4.29289C2.48043 4.10536 2.73478 4 3 4H4V5C4 5.26522 4.10536 5.51957 4.29289 5.70711C4.48043 5.89464 4.73478 6 5 6H11C11.2652 6 11.5196 5.89464 11.7071 5.70711C11.8946 5.51957 12 5.26522 12 5V4H13C13.2652 4 13.5196 4.10536 13.7071 4.29289C13.8946 4.48043 14 4.73478 14 5V17ZM11 8H5C4.73478 8 4.48043 8.10536 4.29289 8.29289C4.10536 8.48043 4 8.73478 4 9C4 9.26522 4.10536 9.51957 4.29289 9.70711C4.48043 9.89464 4.73478 10 5 10H11C11.2652 10 11.5196 9.89464 11.7071 9.70711C11.8946 9.51957 12 9.26522 12 9C12 8.73478 11.8946 8.48043 11.7071 8.29289C11.5196 8.10536 11.2652 8 11 8Z" fill="#382CDD"></path>
                  </svg>
                </span>
                <div>
                  <h4 class="text-sm font-medium"><%= place.name %></h4>
                  <p class="text-xs text-gray-500"><%= place.total %> Cámaras.</p>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</section>